[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
test_speed = 115200
test_framework = custom
build_flags =
  -D CONFIG_BT_NIMBLE_EXT_ADV=1
  -D CONFIG_BT_NIMBLE_MAX_EXT_ADV_INSTANCES=3
lib_deps =
  h2zero/NimBLE-Arduino
  adafruit/Adafruit GFX Library
  adafruit/Adafruit SSD1306

[env:esp32-c3-test]
extends = env:esp32-c3-devkitm-1
test_build_src = yes
build_src_filter = +<*> -<main.cpp>

[env:esp32-c3-fast-cycle]
extends = env:esp32-c3-devkitm-1
build_flags =
  -D CONFIG_BT_NIMBLE_EXT_ADV=1
  -D CONFIG_BT_NIMBLE_MAX_EXT_ADV_INSTANCES=3
  -D ROLE_INTERVAL_OVERRIDE_MS=1000

[env:esp32-c3-fast-cycle-debug]
extends = env:esp32-c3-fast-cycle
build_flags =
  -D CONFIG_BT_NIMBLE_EXT_ADV=1
  -D CONFIG_BT_NIMBLE_MAX_EXT_ADV_INSTANCES=3
  -D ROLE_INTERVAL_OVERRIDE_MS=1000
  -D CONFIG_NIMBLE_CPP_LOG_LEVEL=1
  -D CONFIG_BT_NIMBLE_LOG_LEVEL=3
